# capybara-webkit driver sends log messages generated by
# calling console.log in JavaScript to STDOUT. This means
# we can view deprecation messages generated by jquery-migrate
# when running our Cucumber scenarios.
Capybara.javascript_driver = :webkit
